CREATE TABLE MRD_CUSTOMER (
  CUST_NO      NUMBER(8)     NOT NULL,
  CUST_NAME    VARCHAR2(80)  NOT NULL,
  CUST_STATE   CHAR(1)       NOT NULL,
  CUST_MEMO    VARCHAR2(200),
  CONSTRAINT PK_MRD_CUSTOMER PRIMARY KEY (CUST_NO),
  CONSTRAINT CK_MRD_CUST_STATE CHECK (CUST_STATE IN ('A','I'))
);

CREATE TABLE MRD_ARTICLE (
  ART_NO       NUMBER(8)     NOT NULL,
  ART_DESC     VARCHAR2(80)  NOT NULL,
  ART_PRICE    NUMBER(11,2)  NOT NULL,
  ART_ON_HAND  NUMBER(9)     NOT NULL,
  ART_STATE    CHAR(1)       NOT NULL,
  ART_REV      NUMBER(12)    NOT NULL,
  CONSTRAINT PK_MRD_ARTICLE PRIMARY KEY (ART_NO),
  CONSTRAINT CK_MRD_ART_STATE CHECK (ART_STATE IN ('A','I'))
);

CREATE TABLE MRD_ORDER_HEAD (
  ORD_NO       NUMBER(10)    NOT NULL,
  ORD_CUST     NUMBER(8)     NOT NULL,
  ORD_VALUE    NUMBER(14,2)  NOT NULL,
  ORD_RAISED   DATE          NOT NULL,
  ORD_STATE    VARCHAR2(10)  NOT NULL,
  ORD_REV      NUMBER(12)    NOT NULL,
  CONSTRAINT PK_MRD_ORDER_HEAD PRIMARY KEY (ORD_NO),
  CONSTRAINT FK_MRD_ORDER_CUST FOREIGN KEY (ORD_CUST) REFERENCES MRD_CUSTOMER (CUST_NO),
  CONSTRAINT CK_MRD_ORD_STATE CHECK (ORD_STATE IN ('ENTERED','SHIPPED'))
);

CREATE TABLE MRD_ORDER_ITEM (
  ITM_NO       NUMBER(12)    NOT NULL,
  ITM_ORD      NUMBER(10)    NOT NULL,
  ITM_ART      NUMBER(8)     NOT NULL,
  ITM_QTY      NUMBER(9)     NOT NULL,
  ITM_PRICE    NUMBER(11,2)  NOT NULL,
  ITM_VALUE    NUMBER(14,2)  NOT NULL,
  CONSTRAINT PK_MRD_ORDER_ITEM PRIMARY KEY (ITM_NO),
  CONSTRAINT FK_MRD_ITEM_ORD FOREIGN KEY (ITM_ORD) REFERENCES MRD_ORDER_HEAD (ORD_NO),
  CONSTRAINT FK_MRD_ITEM_ART FOREIGN KEY (ITM_ART) REFERENCES MRD_ARTICLE (ART_NO)
);
