using System.Globalization;
using System.Text;

namespace OracleFormsMigrationFleet.Fleet.Execution;

/// <summary>
/// Emits the PostgreSQL the generated application runs against: the mapped tables, and one PL/pgSQL
/// routine that performs a whole submission atomically.
///
/// The routine exists rather than the equivalent statements being spread through the API because the
/// guarantees asked of it — nothing partial after a refusal, no oversell under concurrency, a total that
/// adds up to the lines stored beside it — are transaction guarantees, and keeping them in one database
/// round trip is what makes them hold when two submissions arrive at once.
/// </summary>
internal static class DotNetTargetDatabaseEmitter
{
    internal static IReadOnlyList<GeneratedFile> Emit(DotNetGenerationPlan plan, List<ConversionFinding> findings) =>
    [
        new GeneratedFile(
            "database/schema.sql",
            Schema(plan, findings),
            "PostgreSQL tables for every mapped object, with the keys, foreign keys, and domains the source declared."),
        new GeneratedFile(
            "database/routines.sql",
            Routine(plan),
            "PL/pgSQL routine performing one submission atomically: validation, header, lines, and stock."),
    ];

    private static string Schema(DotNetGenerationPlan plan, List<ConversionFinding> findings)
    {
        StringBuilder sql = new();
        sql.Append("-- PostgreSQL schema generated by the Oracle Forms Migration Fleet .NET application generator.\n");
        sql.Append("-- Deterministic: no timestamp, host, credential, or random value is embedded.\n");
        sql.Append("-- Every table, column, and constraint below traces to a parsed Oracle object; see mapping-manifest.json.\n\n");

        // Lookups first, then the master, then the detail: a foreign key cannot precede what it references.
        ResolvedObject[] order = [plan.Party, plan.Item, plan.Header, plan.Detail];
        HashSet<string> mapped = new(order.Select(entry => entry.Table.Name), StringComparer.OrdinalIgnoreCase);

        foreach (ResolvedObject entry in order)
        {
            sql.Append(CultureInfo.InvariantCulture, $"-- {entry.Role}: Oracle table {entry.Table.Name}\n");
            sql.Append(CultureInfo.InvariantCulture, $"CREATE TABLE {plan.SqlTable(entry)} (\n");

            List<string> clauses = [];
            string identifier = entry.Require(MappedFieldRole.Identifier).Column.Name;

            foreach (OracleColumn column in entry.Table.Columns)
            {
                string type = plan.TargetType(entry.Table, column);
                bool isIdentifier = string.Equals(column.Name, identifier, StringComparison.OrdinalIgnoreCase);
                MappedFieldRole? role = entry.Fields
                    .FirstOrDefault(field => string.Equals(field.Column.Name, column.Name, StringComparison.OrdinalIgnoreCase))
                    ?.Role;

                StringBuilder clause = new();

                // Provenance goes on its own line. A trailing comment would swallow the comma this clause
                // is later joined with, merging two column definitions into one the target cannot parse.
                clause.Append(CultureInfo.InvariantCulture,
                    $"    -- {column.Name}: {column.RawType} {(role is { } bound ? $"[{bound}]" : "[unmapped]")}\n");
                clause.Append(CultureInfo.InvariantCulture,
                    $"    {DotNetGenerationPlan.Sql(column.Name)} {type}");

                if (isIdentifier)
                {
                    clause.Append(" GENERATED BY DEFAULT AS IDENTITY");
                }

                if (!isIdentifier && column.Default is { Length: > 0 } declared)
                {
                    if (DotNetApplicationEmitter.TranslatableDefault(declared, type) is { } carried)
                    {
                        clause.Append(CultureInfo.InvariantCulture, $" DEFAULT {carried}");
                    }
                    else
                    {
                        findings.Add(new ConversionFinding(
                            ConversionSeverity.ManualReview,
                            "Column default",
                            $"{entry.Table.Name}.{column.Name}",
                            $"The source declares DEFAULT {declared}. Only a literal is carried across, because any " +
                            "other Oracle default expression is not guaranteed to mean the same thing to PostgreSQL. " +
                            "Nothing the generated code writes depends on this one: every column it inserts into, it " +
                            "supplies a value for."));
                    }
                }

                if (column.NotNull && !isIdentifier)
                {
                    clause.Append(" NOT NULL");
                }

                clauses.Add(clause.ToString());
            }

            clauses.Add(
                $"    CONSTRAINT {DotNetGenerationPlan.Sql($"pk_{entry.Table.Name}")} PRIMARY KEY ({DotNetGenerationPlan.Sql(identifier)})");

            foreach (OracleConstraint constraint in entry.Table.Constraints)
            {
                switch (constraint.Kind)
                {
                    case OracleConstraintKind.Unique when constraint.Columns.Count > 0:
                        clauses.Add(
                            $"    UNIQUE ({string.Join(", ", constraint.Columns.Select(DotNetGenerationPlan.Sql))})");
                        break;

                    case OracleConstraintKind.ForeignKey when constraint.ReferencedTable is { Length: > 0 } referenced:
                        if (!mapped.Contains(referenced))
                        {
                            findings.Add(new ConversionFinding(
                                ConversionSeverity.ManualReview,
                                "Foreign key",
                                $"{entry.Table.Name}({string.Join(", ", constraint.Columns)}) -> {referenced}",
                                "The referenced table is not part of this mapping, so the generated database does not " +
                                "create it and the constraint was left out. The column is still created and still holds " +
                                "whatever is loaded into it, unenforced."));
                            break;
                        }

                        string referencedColumns = constraint.ReferencedColumns.Count > 0
                            ? string.Join(", ", constraint.ReferencedColumns.Select(DotNetGenerationPlan.Sql))
                            : DotNetGenerationPlan.Sql(order
                                .First(candidate => string.Equals(candidate.Table.Name, referenced, StringComparison.OrdinalIgnoreCase))
                                .Require(MappedFieldRole.Identifier).Column.Name);

                        clauses.Add(
                            $"    FOREIGN KEY ({string.Join(", ", constraint.Columns.Select(DotNetGenerationPlan.Sql))}) " +
                            $"REFERENCES {DotNetGenerationPlan.Sql(referenced)} ({referencedColumns})");
                        break;

                    case OracleConstraintKind.Check when constraint.CheckExpression is { Length: > 0 } expression:
                        clauses.Add($"    CHECK ({expression})");
                        findings.Add(new ConversionFinding(
                            ConversionSeverity.ManualReview,
                            "Check constraint",
                            $"{entry.Table.Name}: {expression}",
                            "Carried across verbatim. It was not re-evaluated against PostgreSQL semantics, so confirm " +
                            "it still admits and rejects exactly what it did on Oracle."));
                        break;

                    case OracleConstraintKind.PrimaryKey:
                    default:
                        break;
                }
            }

            sql.Append(string.Join(",\n", clauses));
            sql.Append("\n);\n\n");
        }

        sql.Append(CultureInfo.InvariantCulture,
            $"CREATE INDEX {DotNetGenerationPlan.Sql($"ix_{plan.Detail.Table.Name}_parent")} ON {plan.SqlTable(plan.Detail)} " +
            $"({plan.SqlColumn(plan.Detail, MappedFieldRole.ParentReference)});\n");

        return sql.ToString();
    }

    private static string Routine(DotNetGenerationPlan plan)
    {
        ResolvedField partyKey = plan.Party.Require(MappedFieldRole.Identifier);
        ResolvedField itemKey = plan.Item.Require(MappedFieldRole.Identifier);
        ResolvedField headerKey = plan.Header.Require(MappedFieldRole.Identifier);
        ResolvedField total = plan.Header.Require(MappedFieldRole.TotalAmount);
        ResolvedField quantity = plan.Detail.Require(MappedFieldRole.Quantity);
        ResolvedField lineAmount = plan.Detail.Require(MappedFieldRole.LineAmount);
        ResolvedField itemPrice = plan.Item.Require(MappedFieldRole.UnitPrice);
        ResolvedField stock = plan.Item.Require(MappedFieldRole.StockOnHand);

        string lineScale = (lineAmount.Column.Scale ?? 2).ToString(CultureInfo.InvariantCulture);
        string partyFilter = plan.Party.Optional(MappedFieldRole.ActiveFlag) is { } partyFlag
            ? $" AND {DotNetGenerationPlan.Sql(partyFlag.Column.Name)} = {DotNetApplicationEmitter.Literal(plan.Party.Constant(MappedFieldRole.ActiveFlag))}"
            : string.Empty;
        string itemFilter = plan.Item.Optional(MappedFieldRole.ActiveFlag) is { } itemFlag
            ? $" AND {DotNetGenerationPlan.Sql(itemFlag.Column.Name)} = {DotNetApplicationEmitter.Literal(plan.Item.Constant(MappedFieldRole.ActiveFlag))}"
            : string.Empty;

        List<string> headerColumns = [plan.SqlColumn(plan.Header, MappedFieldRole.PartyReference), plan.SqlColumn(plan.Header, MappedFieldRole.TotalAmount), plan.SqlColumn(plan.Header, MappedFieldRole.CreatedAt)];
        List<string> headerValues = ["p_party_id", "0", "now()"];

        if (plan.Header.Optional(MappedFieldRole.Status) is { } status)
        {
            headerColumns.Add(DotNetGenerationPlan.Sql(status.Column.Name));
            headerValues.Add(DotNetApplicationEmitter.Literal(plan.Header.Constant(MappedFieldRole.Status)));
        }

        if (plan.Header.Optional(MappedFieldRole.ConcurrencyVersion) is { } headerVersion)
        {
            headerColumns.Add(DotNetGenerationPlan.Sql(headerVersion.Column.Name));
            headerValues.Add("1");
        }

        StringBuilder sql = new();
        sql.Append("-- PL/pgSQL routine generated by the Oracle Forms Migration Fleet .NET application generator.\n");
        sql.Append("-- SECURITY INVOKER (the default): the routine runs with the caller's privileges and grants none.\n");
        sql.Append(CultureInfo.InvariantCulture,
            $"-- Concurrency control: {(plan.Optimistic ? "optimistic, conditioned on the mapped version column" : "pessimistic, row locks taken in item-identifier order")}.\n\n");

        sql.Append(CultureInfo.InvariantCulture, $"CREATE OR REPLACE FUNCTION {DotNetGenerationPlan.Sql(DotNetApplicationEmitter.RoutineName)}(\n");
        sql.Append(CultureInfo.InvariantCulture, $"    p_party_id {partyKey.PostgreSqlType},\n");
        sql.Append("    p_lines    jsonb\n");
        sql.Append(CultureInfo.InvariantCulture, $")\nRETURNS TABLE (header_id {headerKey.PostgreSqlType}, header_total {total.PostgreSqlType})\n");
        sql.Append("LANGUAGE plpgsql\nAS $ofm$\nDECLARE\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_header_id {headerKey.PostgreSqlType};\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_total     {total.PostgreSqlType} := 0;\n");
        sql.Append("    v_line      jsonb;\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_item_id   {itemKey.PostgreSqlType};\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_quantity  {quantity.PostgreSqlType};\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_price     {itemPrice.PostgreSqlType};\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_stock     {stock.PostgreSqlType};\n");
        sql.Append(CultureInfo.InvariantCulture, $"    v_amount    {lineAmount.PostgreSqlType};\n");

        if (plan.Optimistic)
        {
            sql.Append(CultureInfo.InvariantCulture,
                $"    v_version   {plan.Item.Require(MappedFieldRole.ConcurrencyVersion).PostgreSqlType};\n");
            sql.Append("    v_updated   integer;\n");
        }

        sql.Append("BEGIN\n");
        sql.Append("""
                IF p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
                    RAISE EXCEPTION 'A submission must carry at least one line.' USING ERRCODE = 'OFM03';
                END IF;

                -- Every line is validated before anything is written, so a bad line later in the list cannot
                -- leave earlier stock decrements behind.
                FOR v_line IN SELECT value FROM jsonb_array_elements(p_lines) AS elements(value)
                LOOP
                    IF jsonb_typeof(v_line) <> 'object'
                       OR jsonb_typeof(v_line -> 'itemId') <> 'number'
                       OR jsonb_typeof(v_line -> 'quantity') <> 'number'
                       OR (v_line ->> 'itemId')::numeric <> trunc((v_line ->> 'itemId')::numeric)
                       OR (v_line ->> 'quantity')::numeric <> trunc((v_line ->> 'quantity')::numeric)
                       OR (v_line ->> 'itemId')::numeric NOT BETWEEN 1 AND 9223372036854775807
                       OR (v_line ->> 'quantity')::numeric NOT BETWEEN 1 AND 9223372036854775807 THEN
                        RAISE EXCEPTION 'A line carries an absent, non-integral, or non-positive item reference or quantity.'
                            USING ERRCODE = 'OFM03';
                    END IF;
                END LOOP;


        """.Replace("\r\n", "\n", StringComparison.Ordinal));

        // A raw interpolated literal does not bind to StringBuilder's culture-aware handler overload, and
        // every hole in the blocks below is already a string, so no culture is involved in formatting one.
        sql.Append(
            $"""
                PERFORM 1 FROM {plan.SqlTable(plan.Party)} WHERE {DotNetGenerationPlan.Sql(partyKey.Column.Name)} = p_party_id{partyFilter};
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Party % does not resolve to an available row.', p_party_id USING ERRCODE = 'OFM01';
                END IF;

                INSERT INTO {plan.SqlTable(plan.Header)} ({string.Join(", ", headerColumns)})
                VALUES ({string.Join(", ", headerValues)})
                RETURNING {DotNetGenerationPlan.Sql(headerKey.Column.Name)} INTO v_header_id;

                FOR v_line IN
                    SELECT value
                      FROM jsonb_array_elements(p_lines) WITH ORDINALITY AS elements(value, position)
                     ORDER BY (value ->> 'itemId')::numeric, position
                LOOP
                    v_item_id  := (v_line ->> 'itemId')::{itemKey.PostgreSqlType};
                    v_quantity := (v_line ->> 'quantity')::{quantity.PostgreSqlType};


            """.Replace("\r\n", "\n", StringComparison.Ordinal));

        string itemTable = plan.SqlTable(plan.Item);
        string itemKeyColumn = DotNetGenerationPlan.Sql(itemKey.Column.Name);
        string priceColumn = DotNetGenerationPlan.Sql(itemPrice.Column.Name);
        string stockColumn = DotNetGenerationPlan.Sql(stock.Column.Name);

        if (plan.Optimistic)
        {
            string versionColumn = DotNetGenerationPlan.Sql(
                plan.Item.Require(MappedFieldRole.ConcurrencyVersion).Column.Name);

            sql.Append(
                $"""
                        SELECT {priceColumn}, {stockColumn}, {versionColumn}
                          INTO v_price, v_stock, v_version
                          FROM {itemTable}
                         WHERE {itemKeyColumn} = v_item_id{itemFilter};
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Item % does not resolve to an available row.', v_item_id USING ERRCODE = 'OFM02';
                        END IF;
                        IF v_stock < v_quantity THEN
                            RAISE EXCEPTION 'Item % holds % and % was requested.', v_item_id, v_stock, v_quantity
                                USING ERRCODE = 'OFM04';
                        END IF;

                        -- The version read above is the condition. A competing transaction that decremented the
                        -- same row first makes this match nothing, and nothing written so far survives the raise.
                        UPDATE {itemTable}
                           SET {stockColumn} = {stockColumn} - v_quantity,
                               {versionColumn} = {versionColumn} + 1
                         WHERE {itemKeyColumn} = v_item_id
                           AND {versionColumn} = v_version
                           AND {stockColumn} >= v_quantity;
                        GET DIAGNOSTICS v_updated = ROW_COUNT;
                        IF v_updated = 0 THEN
                            SELECT {stockColumn} INTO v_stock FROM {itemTable} WHERE {itemKeyColumn} = v_item_id;
                            IF v_stock IS NOT NULL AND v_stock < v_quantity THEN
                                RAISE EXCEPTION 'Item % holds % and % was requested.', v_item_id, v_stock, v_quantity
                                    USING ERRCODE = 'OFM04';
                            END IF;
                            RAISE EXCEPTION 'Item % changed between read and write; the submission was refused.', v_item_id
                                USING ERRCODE = 'OFM05';
                        END IF;


                """.Replace("\r\n", "\n", StringComparison.Ordinal));
        }
        else
        {
            sql.Append(
                $"""
                        -- Taken in item-identifier order by the loop above, so two submissions cannot deadlock.
                        SELECT {priceColumn}, {stockColumn}
                          INTO v_price, v_stock
                          FROM {itemTable}
                         WHERE {itemKeyColumn} = v_item_id{itemFilter}
                           FOR UPDATE;
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Item % does not resolve to an available row.', v_item_id USING ERRCODE = 'OFM02';
                        END IF;
                        IF v_stock < v_quantity THEN
                            RAISE EXCEPTION 'Item % holds % and % was requested.', v_item_id, v_stock, v_quantity
                                USING ERRCODE = 'OFM04';
                        END IF;

                        UPDATE {itemTable}
                           SET {stockColumn} = {stockColumn} - v_quantity
                         WHERE {itemKeyColumn} = v_item_id;


                """.Replace("\r\n", "\n", StringComparison.Ordinal));
        }

        sql.Append(
            $"""
                    v_amount := round(v_price * v_quantity, {lineScale});

                    INSERT INTO {plan.SqlTable(plan.Detail)} (
                        {plan.SqlColumn(plan.Detail, MappedFieldRole.ParentReference)},
                        {plan.SqlColumn(plan.Detail, MappedFieldRole.ItemReference)},
                        {plan.SqlColumn(plan.Detail, MappedFieldRole.Quantity)},
                        {plan.SqlColumn(plan.Detail, MappedFieldRole.UnitPrice)},
                        {plan.SqlColumn(plan.Detail, MappedFieldRole.LineAmount)})
                    VALUES (v_header_id, v_item_id, v_quantity, v_price, v_amount);

                    v_total := v_total + v_amount;
                END LOOP;

                UPDATE {plan.SqlTable(plan.Header)}
                   SET {plan.SqlColumn(plan.Header, MappedFieldRole.TotalAmount)} = v_total
                 WHERE {DotNetGenerationPlan.Sql(headerKey.Column.Name)} = v_header_id;

                RETURN QUERY SELECT v_header_id, v_total;
            END;
            $ofm$;

            """.Replace("\r\n", "\n", StringComparison.Ordinal));

        return sql.ToString();
    }
}
