namespace OracleFormsMigrationFleet.Fleet.Execution;

/// <summary>
/// Emits the React and TypeScript master/detail screen over the generated API.
///
/// The screen is generated from roles, so its shape does not depend on what the estate's tables are
/// called. Headings and column labels are derived from the mapped identifiers, which is presentation; no
/// rule, validation, or route is chosen from a name. Nothing computed in the browser is authoritative:
/// the line preview is labelled as a preview and the stored total comes back from the server.
/// </summary>
internal static class DotNetFrontendEmitter
{
    internal static IReadOnlyList<GeneratedFile> Emit(DotNetGenerationPlan plan) =>
    [
        new GeneratedFile(
            "frontend/package.json",
            GeneratedApplicationVerificationTemplates.Read("Generic/package.json"),
            "Pinned React, TypeScript, Vite, and interaction-test dependencies."),
        new GeneratedFile(
            "frontend/package-lock.json",
            GeneratedApplicationVerificationTemplates.Read("Generic/package-lock.json"),
            "Locked dependency tree so `npm ci` installs exactly what was verified."),
        new GeneratedFile("frontend/tsconfig.json", TsConfig(), "Strict TypeScript configuration for the generated UI."),
        new GeneratedFile("frontend/vite.config.ts", ViteConfig(), "Vite build configuration."),
        new GeneratedFile("frontend/index.html", IndexHtml(plan), "Host page for the generated screen."),
        new GeneratedFile("frontend/src/vite-env.d.ts", ViteTypes(), "Vite ambient types."),
        new GeneratedFile("frontend/src/main.tsx", MainModule(), "Browser entry point."),
        new GeneratedFile("frontend/src/types.ts", Types(), "Wire contract shared with the generated API."),
        new GeneratedFile("frontend/src/api.ts", Api(), "Typed client. The API base is configuration, never a literal host."),
        new GeneratedFile("frontend/src/App.tsx", App(plan), "Master/detail screen with both lookups and server-owned totals."),
        new GeneratedFile("frontend/src/App.test.tsx", AppTest(plan), "Executable interaction tests for the generated screen."),
    ];

    private static string TsConfig() =>
        """
        {
          "compilerOptions": {
            "target": "ES2022",
            "useDefineForClassFields": true,
            "lib": ["ES2022", "DOM", "DOM.Iterable"],
            "allowJs": false,
            "skipLibCheck": true,
            "esModuleInterop": true,
            "allowSyntheticDefaultImports": true,
            "strict": true,
            "forceConsistentCasingInFileNames": true,
            "module": "ESNext",
            "moduleResolution": "Bundler",
            "resolveJsonModule": true,
            "isolatedModules": true,
            "noEmit": true,
            "jsx": "react-jsx"
          },
          "include": ["src"],
          "references": []
        }

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string ViteConfig() =>
        """
        import { defineConfig } from "vite";
        import react from "@vitejs/plugin-react";

        export default defineConfig({ plugins: [react()] });

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string ViteTypes() =>
        """
        /// <reference types="vite/client" />

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string MainModule() =>
        """
        import { StrictMode } from "react";
        import { createRoot } from "react-dom/client";
        import App from "./App";

        const root = document.getElementById("root");
        if (!root) throw new Error("React root element was not found.");
        createRoot(root).render(<StrictMode><App /></StrictMode>);

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string IndexHtml(DotNetGenerationPlan plan) =>
        $"""
        <!doctype html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>{DotNetApplicationEmitter.Label(plan.Header.Table.Name)}</title>
          </head>
          <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>
        </html>

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string Types() =>
        """
        // Generated by the Oracle Forms Migration Fleet. Do not edit: regenerate from the mapping manifest.

        export interface Party {
          id: number;
          name: string;
          available: boolean;
        }

        export interface Item {
          id: number;
          name: string;
          unitPrice: number;
          stockOnHand: number;
          available: boolean;
        }

        export interface SubmissionLine {
          id: number;
          itemId: number;
          itemName: string;
          quantity: number;
          unitPrice: number;
          lineAmount: number;
        }

        export interface Submission {
          id: number;
          partyId: number;
          partyName: string;
          createdAt: string;
          total: number;
          status: string | null;
          version: number | null;
          lines: SubmissionLine[];
        }

        export interface Problem {
          code: string;
          message: string;
        }

        export type SubmitResult =
          | { ok: true; submission: Submission }
          | { ok: false; problem: Problem };

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string Api() =>
        """
        // Generated by the Oracle Forms Migration Fleet. Do not edit: regenerate from the mapping manifest.

        import type { Item, Party, Problem, Submission, SubmitResult } from "./types";

        // Configuration, never a literal host: the same bundle has to work in every environment it is
        // deployed to, and a host baked in here would be one nobody can change without a rebuild.
        const base = import.meta.env.VITE_API_BASE ?? "";

        async function readJson<T>(response: Response): Promise<T> {
          if (!response.ok) {
            throw new Error(`Request failed with status ${response.status}.`);
          }
          return (await response.json()) as T;
        }

        export async function listParties(search?: string): Promise<Party[]> {
          const query = search ? `?search=${encodeURIComponent(search)}` : "";
          return readJson<Party[]>(await fetch(`${base}/api/parties${query}`));
        }

        export async function listItems(search?: string): Promise<Item[]> {
          const query = search ? `?search=${encodeURIComponent(search)}` : "";
          return readJson<Item[]>(await fetch(`${base}/api/items${query}`));
        }

        export async function submit(
          partyId: number,
          lines: ReadonlyArray<{ itemId: number; quantity: number }>,
        ): Promise<SubmitResult> {
          const response = await fetch(`${base}/api/submissions`, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ partyId, lines }),
          });

          if (response.status === 201) {
            return { ok: true, submission: (await response.json()) as Submission };
          }

          const problem = (await response.json().catch(() => null)) as Problem | null;
          return {
            ok: false,
            problem: problem ?? { code: "UNKNOWN", message: `The server answered ${response.status}.` },
          };
        }

        """.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string App(DotNetGenerationPlan plan)
    {
        string title = DotNetApplicationEmitter.Label(plan.Header.Table.Name);
        string partyLabel = DotNetApplicationEmitter.Label(plan.Party.Table.Name);
        string itemLabel = DotNetApplicationEmitter.Label(plan.Item.Table.Name);
        string detailLabel = DotNetApplicationEmitter.Label(plan.Detail.Table.Name);
        string quantityLabel = DotNetApplicationEmitter.Label(plan.Detail.Require(MappedFieldRole.Quantity).Column.Name);
        string priceLabel = DotNetApplicationEmitter.Label(plan.Item.Require(MappedFieldRole.UnitPrice).Column.Name);
        string stockLabel = DotNetApplicationEmitter.Label(plan.Item.Require(MappedFieldRole.StockOnHand).Column.Name);
        string amountLabel = DotNetApplicationEmitter.Label(plan.Detail.Require(MappedFieldRole.LineAmount).Column.Name);
        string totalLabel = DotNetApplicationEmitter.Label(plan.Header.Require(MappedFieldRole.TotalAmount).Column.Name);

        return $$""""
        // Generated by the Oracle Forms Migration Fleet. Do not edit: regenerate from the mapping manifest.

        import { useEffect, useState } from "react";
        import { listItems, listParties, submit } from "./api";
        import type { Item, Party, Problem, Submission } from "./types";

        interface DraftLine {
          itemId: number;
          itemName: string;
          quantity: number;
          unitPrice: number;
        }

        const money = (value: number): string => value.toFixed({{plan.Detail.Require(MappedFieldRole.LineAmount).Column.Scale ?? 2}});

        const page = { fontFamily: "system-ui, sans-serif", margin: "1.5rem", maxWidth: "60rem" } as const;

        /**
         * Master/detail entry over the generated API.
         *
         * Every check here is a courtesy to the operator, not a control: the server re-checks the party, the
         * item, the quantity, and the stock inside the transaction that writes, so a browser that skipped all
         * of this could still not oversell or store a total it chose itself.
         */
        export default function App() {
          const [parties, setParties] = useState<Party[]>([]);
          const [items, setItems] = useState<Item[]>([]);
          const [partyId, setPartyId] = useState<number | null>(null);
          const [itemId, setItemId] = useState<number | null>(null);
          const [quantity, setQuantity] = useState<string>("1");
          const [lines, setLines] = useState<DraftLine[]>([]);
          const [saved, setSaved] = useState<Submission | null>(null);
          const [problem, setProblem] = useState<Problem | null>(null);
          const [busy, setBusy] = useState(false);
          const [loadError, setLoadError] = useState<string | null>(null);

          useEffect(() => {
            let cancelled = false;
            Promise.all([listParties(), listItems()])
              .then(([loadedParties, loadedItems]) => {
                if (cancelled) return;
                setParties(loadedParties);
                setItems(loadedItems);
              })
              .catch((error: unknown) => {
                if (!cancelled) setLoadError(error instanceof Error ? error.message : String(error));
              });
            return () => {
              cancelled = true;
            };
          }, []);

          const chosenItem = items.find((item) => item.id === itemId) ?? null;
          const parsedQuantity = Number(quantity);
          const quantityIsWhole = quantity.trim() !== "" && Number.isInteger(parsedQuantity) && parsedQuantity >= 1;
          const alreadyDrafted = chosenItem
            ? lines.filter((line) => line.itemId === chosenItem.id).reduce((sum, line) => sum + line.quantity, 0)
            : 0;
          const withinStock = chosenItem ? alreadyDrafted + parsedQuantity <= chosenItem.stockOnHand : false;
          const canAdd = chosenItem !== null && quantityIsWhole && withinStock;
          const previewTotal = lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0);

          const addLine = () => {
            if (!chosenItem || !quantityIsWhole || !withinStock) return;
            setLines((current) => [
              ...current,
              {
                itemId: chosenItem.id,
                itemName: chosenItem.name,
                quantity: parsedQuantity,
                unitPrice: chosenItem.unitPrice,
              },
            ]);
            setQuantity("1");
          };

          const removeLine = (index: number) =>
            setLines((current) => current.filter((_, position) => position !== index));

          const send = async () => {
            if (partyId === null || lines.length === 0 || busy) return;
            setBusy(true);
            setProblem(null);
            try {
              const result = await submit(
                partyId,
                lines.map((line) => ({ itemId: line.itemId, quantity: line.quantity })),
              );
              if (result.ok) {
                setSaved(result.submission);
                setLines([]);
                // The stock the lookup reported is now stale; re-read it rather than adjusting it here.
                setItems(await listItems());
              } else {
                setProblem(result.problem);
              }
            } catch (error: unknown) {
              setProblem({ code: "NETWORK", message: error instanceof Error ? error.message : String(error) });
            } finally {
              setBusy(false);
            }
          };

          if (loadError) {
            return <main><p role="alert" data-testid="load-error">{loadError}</p></main>;
          }

          return (
            <main style={page}>
              <h1>{{title}}</h1>

              <section>
                <h2>{{partyLabel}}</h2>
                <label htmlFor="party">{{partyLabel}}</label>
                <select
                  id="party"
                  data-testid="party"
                  value={partyId ?? ""}
                  onChange={(event) => setPartyId(event.target.value === "" ? null : Number(event.target.value))}
                >
                  <option value="">Choose…</option>
                  {parties.filter((party) => party.available).map((party) => (
                    <option key={party.id} value={party.id}>{party.name}</option>
                  ))}
                </select>
              </section>

              <section>
                <h2>{{detailLabel}}</h2>
                <label htmlFor="item">{{itemLabel}}</label>
                <select
                  id="item"
                  data-testid="item"
                  value={itemId ?? ""}
                  onChange={(event) => setItemId(event.target.value === "" ? null : Number(event.target.value))}
                >
                  <option value="">Choose…</option>
                  {items.filter((item) => item.available).map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.name} — {{priceLabel}} {money(item.unitPrice)} — {{stockLabel}} {item.stockOnHand}
                    </option>
                  ))}
                </select>

                <label htmlFor="quantity">{{quantityLabel}}</label>
                <input
                  id="quantity"
                  data-testid="quantity"
                  inputMode="numeric"
                  value={quantity}
                  onChange={(event) => setQuantity(event.target.value)}
                />

                <button type="button" data-testid="add" disabled={!canAdd} onClick={addLine}>Add line</button>

                {chosenItem && !quantityIsWhole && (
                  <p role="alert" data-testid="quantity-error">
                    {{quantityLabel}} has to be a whole number of at least one.
                  </p>
                )}
                {chosenItem && quantityIsWhole && !withinStock && (
                  <p role="alert" data-testid="stock-error">
                    {{stockLabel}} for {chosenItem.name} is {chosenItem.stockOnHand}; this submission already draws
                    {" "}{alreadyDrafted}. The server refuses the rest regardless of what this screen shows.
                  </p>
                )}
              </section>

              <table data-testid="lines">
                <thead>
                  <tr>
                    <th>{{itemLabel}}</th>
                    <th>{{quantityLabel}}</th>
                    <th>{{priceLabel}}</th>
                    <th>{{amountLabel}} (preview)</th>
                    <th />
                  </tr>
                </thead>
                <tbody>
                  {lines.map((line, index) => (
                    <tr key={`${line.itemId}-${index}`}>
                      <td>{line.itemName}</td>
                      <td>{line.quantity}</td>
                      <td>{money(line.unitPrice)}</td>
                      <td>{money(line.unitPrice * line.quantity)}</td>
                      <td>
                        <button type="button" onClick={() => removeLine(index)}>Remove</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <p data-testid="preview-total">Preview {{totalLabel}}: {money(previewTotal)} (not authoritative)</p>

              <button
                type="button"
                data-testid="submit"
                disabled={partyId === null || lines.length === 0 || busy}
                onClick={send}
              >
                {busy ? "Saving…" : "Save"}
              </button>

              {problem && (
                <p role="alert" data-testid="problem">{problem.code}: {problem.message}</p>
              )}

              {saved && (
                <section data-testid="saved">
                  <h2>Saved</h2>
                  <p data-testid="saved-total">{{totalLabel}}: {money(saved.total)}</p>
                  <ul>
                    {saved.lines.map((line) => (
                      <li key={line.id}>
                        {line.itemName} × {line.quantity} @ {money(line.unitPrice)} = {money(line.lineAmount)}
                      </li>
                    ))}
                  </ul>
                  <p>Every value above was read back from the server after it stored the submission.</p>
                </section>
              )}
            </main>
          );
        }

        """".Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static string AppTest(DotNetGenerationPlan plan)
    {
        int scale = plan.Detail.Require(MappedFieldRole.LineAmount).Column.Scale ?? 2;

        return $$""""
        // Generated by the Oracle Forms Migration Fleet. Do not edit: regenerate from the mapping manifest.

        import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
        import { afterEach, describe, expect, it, vi } from "vitest";
        import App from "./App";

        const parties = [{ id: 11, name: "Chosen party", available: true }];
        const items = [{ id: 21, name: "Chosen item", unitPrice: 12.5, stockOnHand: 4, available: true }];

        const json = (body: unknown, status = 200) =>
          new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });

        function stubFetch(onSubmit: (body: string) => Response) {
          const calls: string[] = [];
          vi.stubGlobal(
            "fetch",
            vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
              const url = String(input);
              calls.push(url);
              if (url.includes("/api/parties")) return json(parties);
              if (url.includes("/api/items")) return json(items);
              if (url.includes("/api/submissions")) return onSubmit(String(init?.body ?? ""));
              return json({ code: "NOTFOUND", message: "no route" }, 404);
            }),
          );
          return calls;
        }

        // The suite runs without vitest globals, so Testing Library never registers its own automatic
        // cleanup and every render would otherwise stay in the document for the cases that follow. That
        // leaves two of each element behind and getByTestId fails on the duplicate rather than on the
        // behaviour under test. Unmounting here is what keeps each case reading its own screen; narrowing
        // the queries instead would only hide the leak.
        afterEach(() => {
          cleanup();
          vi.unstubAllGlobals();
        });

        describe("generated master/detail screen", () => {
          it("renders the total the server stored, not the one the browser previewed", async () => {
            stubFetch(() =>
              json(
                {
                  id: 7,
                  partyId: 11,
                  partyName: "Chosen party",
                  createdAt: "2026-01-01T00:00:00",
                  total: 25.0,
                  status: null,
                  version: null,
                  lines: [
                    { id: 1, itemId: 21, itemName: "Chosen item", quantity: 2, unitPrice: 12.5, lineAmount: 25.0 },
                  ],
                },
                201,
              ),
            );

            render(<App />);
            fireEvent.change(await screen.findByTestId("party"), { target: { value: "11" } });
            fireEvent.change(screen.getByTestId("item"), { target: { value: "21" } });
            fireEvent.change(screen.getByTestId("quantity"), { target: { value: "2" } });
            fireEvent.click(screen.getByTestId("add"));
            fireEvent.click(screen.getByTestId("submit"));

            const total = await screen.findByTestId("saved-total");
            expect(total.textContent).toContain((25).toFixed({{scale}}));
          });

          it("will not add a fractional or non-positive quantity", async () => {
            const calls = stubFetch(() => json({ code: "OFM03", message: "unreachable" }, 422));

            render(<App />);
            fireEvent.change(await screen.findByTestId("party"), { target: { value: "11" } });
            fireEvent.change(screen.getByTestId("item"), { target: { value: "21" } });

            for (const bad of ["2.5", "0", "-1", ""]) {
              fireEvent.change(screen.getByTestId("quantity"), { target: { value: bad } });
              expect((screen.getByTestId("add") as HTMLButtonElement).disabled).toBe(true);
            }

            expect(screen.getByTestId("quantity-error")).toBeTruthy();
            expect(calls.some((call) => call.includes("/api/submissions"))).toBe(false);
          });

          it("will not draft more than the reported stock", async () => {
            stubFetch(() => json({ code: "OFM04", message: "unreachable" }, 409));

            render(<App />);
            fireEvent.change(await screen.findByTestId("party"), { target: { value: "11" } });
            fireEvent.change(screen.getByTestId("item"), { target: { value: "21" } });
            fireEvent.change(screen.getByTestId("quantity"), { target: { value: "5" } });

            expect((screen.getByTestId("add") as HTMLButtonElement).disabled).toBe(true);
            expect(screen.getByTestId("stock-error")).toBeTruthy();
          });

          it("shows the server's refusal and keeps the draft", async () => {
            stubFetch(() => json({ code: "OFM04", message: "Item 21 holds 4 and 6 was requested." }, 409));

            render(<App />);
            fireEvent.change(await screen.findByTestId("party"), { target: { value: "11" } });
            fireEvent.change(screen.getByTestId("item"), { target: { value: "21" } });
            fireEvent.change(screen.getByTestId("quantity"), { target: { value: "2" } });
            fireEvent.click(screen.getByTestId("add"));
            fireEvent.click(screen.getByTestId("submit"));

            const problem = await screen.findByTestId("problem");
            expect(problem.textContent).toContain("OFM04");
            await waitFor(() => expect(screen.queryByTestId("saved")).toBeNull());
          });
        });

        """".Replace("\r\n", "\n", StringComparison.Ordinal);
    }
}
