// Copyright (c) Microsoft. All rights reserved.

using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace OracleFormsMigrationFleet.Fleet.Execution;

/// <summary>How much human work a converted construct still needs.</summary>
public enum ConversionSeverity
{
    /// <summary>Converted faithfully; recorded so the mapping stays auditable.</summary>
    Note,

    /// <summary>Converted, but Oracle and PostgreSQL semantics are not guaranteed to agree.</summary>
    ManualReview,

    /// <summary>Not converted at all. A human has to rewrite it.</summary>
    Unsupported,
}

public sealed record ConversionFinding(
    ConversionSeverity Severity,
    string Category,
    string Construct,
    string Reason);

public sealed record TypeMapping(string Table, string Column, string OracleType, string PostgreSqlType);

public sealed record ConversionReport(
    int Tables,
    int Columns,
    int Constraints,
    int Sequences,
    int Indexes,
    IReadOnlyList<TypeMapping> TypeMappings,
    IReadOnlyList<ConversionFinding> Findings);

public sealed record PostgreSqlConversion(string Ddl, ConversionReport Report);

/// <summary>
/// Converts a parsed Oracle schema to PostgreSQL DDL. Pure: no file, process, or network access, and no
/// timestamp is embedded in the generated SQL so repeated runs over the same input are byte-identical.
/// PL/SQL bodies are never translated; they are reported as manual PL/pgSQL rewrites.
/// </summary>
public static partial class PostgreSqlEmitter
{
    private static readonly HashSet<string> s_reserved = new(StringComparer.Ordinal)
    {
        "all", "analyse", "analyze", "and", "any", "array", "as", "asc", "asymmetric", "authorization",
        "binary", "both", "case", "cast", "check", "collate", "collation", "column", "concurrently",
        "constraint", "create", "cross", "current_catalog", "current_date", "current_role", "current_schema",
        "current_time", "current_timestamp", "current_user", "default", "deferrable", "desc", "distinct",
        "do", "else", "end", "except", "false", "fetch", "for", "foreign", "freeze", "from", "full",
        "grant", "group", "having", "ilike", "in", "initially", "inner", "intersect", "into", "is",
        "isnull", "join", "lateral", "leading", "left", "like", "limit", "localtime", "localtimestamp",
        "natural", "not", "notnull", "null", "offset", "on", "only", "or", "order", "outer", "overlaps",
        "placing", "primary", "references", "returning", "right", "select", "session_user", "similar",
        "some", "symmetric", "table", "tablesample", "then", "to", "trailing", "true", "union", "unique",
        "user", "using", "variadic", "verbose", "when", "where", "window", "with",
    };

    /// <summary>Oracle-only constructs that this converter deliberately refuses to translate automatically.</summary>
    private static readonly (string Construct, string Reason)[] s_plSqlConstructs =
    [
        ("PACKAGE", "Packages have no PostgreSQL equivalent. Split the specification and body into schema-qualified functions and rewrite the body in PL/pgSQL by hand."),
        ("PROCEDURE", "Stored procedure bodies are not translated by this converter. Rewrite them in PL/pgSQL by hand."),
        ("FUNCTION", "Stored function bodies are not translated by this converter. Rewrite them in PL/pgSQL by hand."),
        ("TRIGGER", "Oracle triggers carry row-level semantics and :NEW/:OLD bindings that differ from PostgreSQL. Rewrite as a PL/pgSQL trigger function plus CREATE TRIGGER by hand."),
        ("%ROWTYPE", "%ROWTYPE anchoring is Oracle-specific. PostgreSQL offers table-name row types with different NULL and assignment behaviour; rewrite by hand."),
        ("CONNECT BY", "Hierarchical CONNECT BY queries must be rewritten as recursive common table expressions by hand."),
        ("DUAL", "SELECT ... FROM DUAL must be rewritten as a bare SELECT."),
        ("ROWNUM", "ROWNUM must be rewritten using LIMIT, FETCH FIRST, or ROW_NUMBER(); the filter position semantics differ."),
        ("STANDARD_HASH", "STANDARD_HASH has no PostgreSQL equivalent. Use pgcrypto digest() and re-verify every stored hash value before switching."),
    ];

    public static PostgreSqlConversion Convert(OracleSchema schema, string? oracleText = null)
    {
        ArgumentNullException.ThrowIfNull(schema);

        List<TypeMapping> mappings = [];
        List<ConversionFinding> findings = [];
        StringBuilder ddl = new();

        PlSqlTranslation translation = PlSqlTranslator.Translate(oracleText);
        findings.AddRange(translation.Findings);

        void Line(string text = "") => ddl.Append(text).Append('\n');

        Line("-- PostgreSQL DDL generated by the Oracle Forms Migration Fleet database conversion adapter.");
        Line("-- Deterministic output: no timestamp, host, or credential is embedded.");
        Line("-- Translated program units are translated, not verified. See conversion-report.md.");
        Line();

        foreach (OracleSequence sequence in schema.Sequences)
        {
            List<string> clauses = [];
            if (sequence.StartWith is long start)
            {
                clauses.Add($"START WITH {start.ToString(CultureInfo.InvariantCulture)}");
            }

            if (sequence.IncrementBy is long increment)
            {
                clauses.Add($"INCREMENT BY {increment.ToString(CultureInfo.InvariantCulture)}");
            }

            string tail = clauses.Count > 0 ? " " + string.Join(' ', clauses) : string.Empty;
            Line($"CREATE SEQUENCE {Identifier(sequence.Name)}{tail};");
        }

        if (schema.Sequences.Count > 0)
        {
            Line();
        }

        int constraintCount = 0;
        List<(OracleTable Table, OracleConstraint Constraint)> foreignKeys = [];
        HashSet<string> knownTables = new(schema.Tables.Select(table => table.Name), StringComparer.OrdinalIgnoreCase);

        foreach (OracleTable table in schema.Tables)
        {
            List<string> items = [];

            foreach (OracleColumn column in table.Columns)
            {
                string type = MapType(table.Name, column, mappings, findings);
                StringBuilder definition = new($"    {Identifier(column.Name)} {type}");

                if (column.Default is string oracleDefault)
                {
                    definition.Append(" DEFAULT ").Append(ConvertExpression(oracleDefault, findings));
                }

                if (column.NotNull)
                {
                    definition.Append(" NOT NULL");
                }

                items.Add(definition.ToString());
            }

            foreach (OracleConstraint constraint in table.Constraints)
            {
                constraintCount++;

                if (constraint.Kind == OracleConstraintKind.ForeignKey)
                {
                    foreignKeys.Add((table, constraint));
                    continue;
                }

                if (RenderTableConstraint(table, constraint, findings) is string rendered)
                {
                    items.Add("    " + rendered);
                }
            }

            Line($"CREATE TABLE {Identifier(table.Name)} (");
            Line(string.Join(",\n", items));
            Line(");");
            Line();
        }

        foreach ((OracleTable table, OracleConstraint constraint) in foreignKeys)
        {
            if (constraint.ReferencedTable is not string referenced)
            {
                findings.Add(new ConversionFinding(
                    ConversionSeverity.Unsupported,
                    "Constraint",
                    $"{table.Name}.{constraint.Name ?? "FOREIGN KEY"}",
                    "The foreign key has no resolvable referenced table and was not emitted."));
                continue;
            }

            if (!knownTables.Contains(referenced))
            {
                findings.Add(new ConversionFinding(
                    ConversionSeverity.ManualReview,
                    "Constraint",
                    $"{table.Name}.{constraint.Name ?? "FOREIGN KEY"}",
                    $"References table '{referenced}', which is not defined in the supplied DDL. The statement is emitted but will fail until that table exists."));
            }

            string name = constraint.Name is string given ? $"CONSTRAINT {Identifier(given)} " : string.Empty;
            string columns = string.Join(", ", constraint.Columns.Select(Identifier));
            string targetColumns = constraint.ReferencedColumns.Count > 0
                ? $" ({string.Join(", ", constraint.ReferencedColumns.Select(Identifier))})"
                : string.Empty;

            Line($"ALTER TABLE {Identifier(table.Name)} ADD {name}FOREIGN KEY ({columns}) REFERENCES {Identifier(referenced)}{targetColumns};");
        }

        if (foreignKeys.Count > 0)
        {
            Line();
        }

        foreach (OracleIndex index in schema.Indexes)
        {
            string unique = index.IsUnique ? "UNIQUE " : string.Empty;
            string columns = string.Join(", ", index.Columns.Select(IdentifierOrExpression));
            Line($"CREATE {unique}INDEX {Identifier(index.Name)} ON {Identifier(index.Table)} ({columns});");
        }

        AddSchemaWideFindings(schema, oracleText, findings, translation);

        string programUnits = PlSqlTranslator.Render(translation.Units);
        if (programUnits.Length > 0)
        {
            ddl.Append(programUnits);
        }

        ConversionReport report = new(
            schema.Tables.Count,
            schema.Tables.Sum(table => table.Columns.Count),
            constraintCount,
            schema.Sequences.Count,
            schema.Indexes.Count,
            mappings,
            Deduplicate(findings));

        return new PostgreSqlConversion(ddl.ToString(), report);
    }

    private static string? RenderTableConstraint(OracleTable table, OracleConstraint constraint, List<ConversionFinding> findings)
    {
        string name = constraint.Name is string given ? $"CONSTRAINT {Identifier(given)} " : string.Empty;

        switch (constraint.Kind)
        {
            case OracleConstraintKind.PrimaryKey:
                return $"{name}PRIMARY KEY ({string.Join(", ", constraint.Columns.Select(Identifier))})";

            case OracleConstraintKind.Unique:
                return $"{name}UNIQUE ({string.Join(", ", constraint.Columns.Select(Identifier))})";

            case OracleConstraintKind.Check when constraint.CheckExpression is string expression:
                findings.Add(new ConversionFinding(
                    ConversionSeverity.ManualReview,
                    "Check constraint",
                    $"{table.Name}.{constraint.Name ?? "CHECK"}",
                    "The Oracle expression was copied verbatim. Oracle and PostgreSQL differ on empty-string/NULL handling, implicit conversion, and NLS-sensitive comparison, so the constraint must be re-tested before use."));
                return $"{name}CHECK ({Whitespace().Replace(expression, " ").Trim()})";

            default:
                return null;
        }
    }

    private static string MapType(
        string table,
        OracleColumn column,
        List<TypeMapping> mappings,
        List<ConversionFinding> findings)
    {
        string qualified = $"{table}.{column.Name}";
        string mapped = column.BaseType switch
        {
            "NUMBER" or "NUMERIC" or "DECIMAL" or "DEC" => MapNumber(qualified, column, findings),
            "INTEGER" or "INT" => "integer",
            "SMALLINT" => "smallint",
            "FLOAT" => "double precision",
            "REAL" or "BINARY_FLOAT" => "real",
            "BINARY_DOUBLE" or "DOUBLE PRECISION" => "double precision",
            "VARCHAR2" or "VARCHAR" or "NVARCHAR2" => Sized("varchar", column.Precision),
            "CHAR" or "NCHAR" => Sized("char", column.Precision),
            "CLOB" or "NCLOB" or "LONG" => "text",
            "BLOB" or "LONG RAW" => "bytea",
            "RAW" => MapRaw(qualified, column, findings),
            "BFILE" => Unsupported(qualified, "BFILE", "BFILE is an external file locator with no PostgreSQL equivalent. Column mapped to bytea; move the payload or replace the locator by hand.", "bytea", findings),
            "DATE" => MapDate(qualified, findings),
            "TIMESTAMP" => Sized("timestamp", column.Precision),
            "TIMESTAMP WITH TIME ZONE" => "timestamptz",
            "TIMESTAMP WITH LOCAL TIME ZONE" => MapLocalTimestamp(qualified, findings),
            "INTERVAL YEAR TO MONTH" or "INTERVAL DAY TO SECOND" => "interval",
            "XMLTYPE" => "xml",
            "BOOLEAN" => "boolean",
            "ROWID" or "UROWID" => Unsupported(qualified, column.BaseType, "Oracle physical row identifiers have no PostgreSQL equivalent. Column mapped to text; replace every ROWID dependency with a surrogate key.", "text", findings),
            _ => Unsupported(qualified, column.BaseType, "The Oracle type was not recognised by this converter. Column mapped to text so the DDL stays valid; supply the correct type by hand.", "text", findings),
        };

        mappings.Add(new TypeMapping(table, column.Name, column.RawType, mapped));
        return mapped;
    }

    private static string MapNumber(string qualified, OracleColumn column, List<ConversionFinding> findings)
    {
        if (column.Precision is not int precision)
        {
            findings.Add(new ConversionFinding(
                ConversionSeverity.ManualReview,
                "NUMBER precision loss",
                qualified,
                "Oracle NUMBER without precision holds up to 38 significant digits. Mapped to unconstrained numeric; confirm the application does not rely on Oracle's rounding or storage behaviour."));
            return "numeric";
        }

        int scale = column.Scale ?? 0;
        if (scale != 0)
        {
            return $"numeric({precision.ToString(CultureInfo.InvariantCulture)},{scale.ToString(CultureInfo.InvariantCulture)})";
        }

        if (precision <= 9)
        {
            return "integer";
        }

        if (precision <= 18)
        {
            return "bigint";
        }

        findings.Add(new ConversionFinding(
            ConversionSeverity.ManualReview,
            "NUMBER precision loss",
            qualified,
            $"NUMBER({precision.ToString(CultureInfo.InvariantCulture)}) exceeds the 64-bit integer range and was mapped to numeric({precision.ToString(CultureInfo.InvariantCulture)}). Arithmetic performance and overflow behaviour differ from Oracle."));
        return $"numeric({precision.ToString(CultureInfo.InvariantCulture)})";
    }

    private static string MapRaw(string qualified, OracleColumn column, List<ConversionFinding> findings)
    {
        findings.Add(new ConversionFinding(
            ConversionSeverity.ManualReview,
            "RAW",
            qualified,
            column.Precision is int length
                ? $"RAW({length.ToString(CultureInfo.InvariantCulture)}) was mapped to bytea, which does not enforce a maximum length. Add a length CHECK if the limit is load-bearing."
                : "RAW was mapped to bytea, which does not enforce a maximum length."));
        return "bytea";
    }

    private static string MapDate(string qualified, List<ConversionFinding> findings)
    {
        findings.Add(new ConversionFinding(
            ConversionSeverity.ManualReview,
            "DATE semantics",
            qualified,
            "Oracle DATE carries a time component; PostgreSQL date does not. If the column stores a time of day, change the target type to timestamp before loading data."));
        return "date";
    }

    private static string MapLocalTimestamp(string qualified, List<ConversionFinding> findings)
    {
        findings.Add(new ConversionFinding(
            ConversionSeverity.ManualReview,
            "TIMESTAMP WITH LOCAL TIME ZONE",
            qualified,
            "Oracle normalises this type to the database time zone and renders it in the session time zone. Mapped to timestamptz; verify the session time zone assumptions of every caller."));
        return "timestamptz";
    }

    private static string Unsupported(
        string qualified,
        string construct,
        string reason,
        string fallback,
        List<ConversionFinding> findings)
    {
        findings.Add(new ConversionFinding(ConversionSeverity.Unsupported, "Type", $"{construct} at {qualified}", reason));
        return fallback;
    }

    private static string Sized(string type, int? length) =>
        length is int value && value > 0
            ? $"{type}({value.ToString(CultureInfo.InvariantCulture)})"
            : type == "varchar" ? "text" : type;

    private static void AddSchemaWideFindings(
        OracleSchema schema, string? oracleText, List<ConversionFinding> findings, PlSqlTranslation translation)
    {
        bool hasVarchar2 = schema.Tables
            .SelectMany(table => table.Columns)
            .Any(column => column.BaseType is "VARCHAR2" or "NVARCHAR2");

        if (hasVarchar2)
        {
            findings.Add(new ConversionFinding(
                ConversionSeverity.ManualReview,
                "VARCHAR2 semantics",
                "VARCHAR2 columns",
                "Oracle stores the empty string as NULL; PostgreSQL treats '' and NULL as different values. Every IS NULL test, NOT NULL constraint, and equality comparison over a converted VARCHAR2 column must be re-verified."));
        }

        string haystack = string.Join('\n', schema.Unparsed.Append(oracleText ?? string.Empty));
        if (haystack.Length == 0)
        {
            return;
        }

        string masked = haystack.ToUpperInvariant();

        // A construct the translator handled is no longer outstanding work, and listing it as unconvertible
        // next to the SQL that converted it would make the report contradict the artifact.
        string rendered = PlSqlTranslator.Render(translation.Units).ToUpperInvariant();
        HashSet<string> translated = new(StringComparer.Ordinal);

        foreach (PlSqlUnit unit in translation.Units.Where(unit => unit.Sql.Length > 0))
        {
            switch (unit.Kind)
            {
                case PlSqlUnitKind.Function:
                case PlSqlUnitKind.Procedure:
                    translated.Add(unit.Kind == PlSqlUnitKind.Function ? "FUNCTION" : "PROCEDURE");
                    translated.Add("PACKAGE");
                    translated.Add("%ROWTYPE");
                    break;
                case PlSqlUnitKind.Trigger:
                    translated.Add("TRIGGER");
                    break;
            }
        }

        // Only claim the hash was handled if none survived the rewrite.
        if (translated.Count > 0 && !rendered.Contains("STANDARD_HASH", StringComparison.Ordinal))
        {
            translated.Add("STANDARD_HASH");
        }

        foreach ((string construct, string reason) in s_plSqlConstructs)
        {
            if (!translated.Contains(construct) && ConstructPattern(construct).IsMatch(masked))
            {
                findings.Add(new ConversionFinding(ConversionSeverity.Unsupported, "Oracle-only construct", construct, reason));
            }
        }
    }

    private static Regex ConstructPattern(string construct) => construct switch
    {
        "PACKAGE" => PackagePattern(),
        "PROCEDURE" => ProcedurePattern(),
        "FUNCTION" => FunctionPattern(),
        "TRIGGER" => TriggerPattern(),
        "%ROWTYPE" => RowTypePattern(),
        "CONNECT BY" => ConnectByPattern(),
        "DUAL" => DualPattern(),
        "ROWNUM" => RowNumPattern(),
        _ => StandardHashPattern(),
    };

    private static string ConvertExpression(string expression, List<ConversionFinding> findings)
    {
        string converted = SysGuid().Replace(expression, "gen_random_uuid()");
        if (!string.Equals(converted, expression, StringComparison.Ordinal))
        {
            findings.Add(new ConversionFinding(
                ConversionSeverity.Note,
                "Default expression",
                "SYS_GUID()",
                "Replaced with gen_random_uuid(), which requires PostgreSQL 13 or later. The generated value is a UUID, not Oracle's 16-byte RAW."));
        }

        converted = SysTimestamp().Replace(converted, "now()");
        converted = SysDate().Replace(converted, "CURRENT_DATE");
        return Whitespace().Replace(converted, " ").Trim();
    }

    private static IReadOnlyList<ConversionFinding> Deduplicate(List<ConversionFinding> findings)
    {
        HashSet<string> seen = new(StringComparer.Ordinal);
        List<ConversionFinding> unique = [];

        foreach (ConversionFinding finding in findings)
        {
            if (seen.Add($"{finding.Severity}|{finding.Category}|{finding.Construct}|{finding.Reason}"))
            {
                unique.Add(finding);
            }
        }

        return unique;
    }

    private static string IdentifierOrExpression(string value) =>
        SimpleName().IsMatch(value.Trim()) ? Identifier(value) : value.Trim();

    /// <summary>Lower-cases to the PostgreSQL default folding and quotes only when the result would not parse.</summary>
    public static string Identifier(string name)
    {
        string lowered = name.Trim().ToLowerInvariant();
        return BareIdentifier().IsMatch(lowered) && !s_reserved.Contains(lowered)
            ? lowered
            : $"\"{lowered.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";
    }

    /// <summary>Renders the conversion report as Markdown. Pure: no timestamp and no file access.</summary>
    public static string RenderReport(ConversionReport report, string applicationName)
    {
        ArgumentNullException.ThrowIfNull(report);

        StringBuilder markdown = new();
        void Line(string text = "") => markdown.Append(text).Append('\n');

        Line("# PostgreSQL conversion report");
        Line();
        Line($"Application: {applicationName}");
        Line("Target: PostgreSQL");
        Line();
        Line("This report describes a schema conversion only. No database was contacted, no data was moved,");
        Line("and no PL/SQL program unit was translated. Every item under \"Manual rewrite required\" and");
        Line("\"Manual review required\" is outstanding work for a human.");
        Line();
        Line("## Converted objects");
        Line();
        Line("| Object | Count |");
        Line("| --- | --- |");
        Line($"| Tables | {report.Tables.ToString(CultureInfo.InvariantCulture)} |");
        Line($"| Columns | {report.Columns.ToString(CultureInfo.InvariantCulture)} |");
        Line($"| Constraints | {report.Constraints.ToString(CultureInfo.InvariantCulture)} |");
        Line($"| Sequences | {report.Sequences.ToString(CultureInfo.InvariantCulture)} |");
        Line($"| Indexes | {report.Indexes.ToString(CultureInfo.InvariantCulture)} |");
        Line();
        Line("## Type mappings applied");
        Line();

        if (report.TypeMappings.Count == 0)
        {
            Line("No columns were converted.");
        }
        else
        {
            Line("| Table | Column | Oracle | PostgreSQL |");
            Line("| --- | --- | --- | --- |");
            foreach (TypeMapping mapping in report.TypeMappings)
            {
                Line($"| {mapping.Table} | {mapping.Column} | {mapping.OracleType} | {mapping.PostgreSqlType} |");
            }
        }

        Line();
        Section(Line, report, ConversionSeverity.Unsupported, "Manual rewrite required", "No unconvertible construct was detected in the supplied input.");
        Section(Line, report, ConversionSeverity.ManualReview, "Manual review required", "No construct needed review.");
        Section(Line, report, ConversionSeverity.Note, "Notes", "No additional notes.");

        return markdown.ToString();
    }

    private static void Section(
        Action<string> line,
        ConversionReport report,
        ConversionSeverity severity,
        string heading,
        string empty)
    {
        IReadOnlyList<ConversionFinding> selected = [.. report.Findings.Where(finding => finding.Severity == severity)];

        line($"## {heading} ({selected.Count.ToString(CultureInfo.InvariantCulture)})");
        line(string.Empty);

        if (selected.Count == 0)
        {
            line(empty);
        }
        else
        {
            foreach (ConversionFinding finding in selected)
            {
                line($"- **{finding.Category} — {finding.Construct}**: {finding.Reason}");
            }
        }

        line(string.Empty);
    }

    [GeneratedRegex(@"^[a-z_][a-z0-9_$]*$", RegexOptions.CultureInvariant)]
    private static partial Regex BareIdentifier();

    /// <summary>An index key that is a plain column name rather than an expression.</summary>
    [GeneratedRegex(@"^[A-Za-z_][A-Za-z0-9_$]*$", RegexOptions.CultureInvariant)]
    private static partial Regex SimpleName();

    [GeneratedRegex(@"\bSYS_GUID\s*\(\s*\)", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex SysGuid();

    [GeneratedRegex(@"\bSYSTIMESTAMP\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex SysTimestamp();

    [GeneratedRegex(@"\bSYSDATE\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex SysDate();

    [GeneratedRegex(@"\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:EDITIONABLE\s+|NONEDITIONABLE\s+)?PACKAGE\b", RegexOptions.CultureInvariant)]
    private static partial Regex PackagePattern();

    [GeneratedRegex(@"\bPROCEDURE\b", RegexOptions.CultureInvariant)]
    private static partial Regex ProcedurePattern();

    [GeneratedRegex(@"\bFUNCTION\b", RegexOptions.CultureInvariant)]
    private static partial Regex FunctionPattern();

    [GeneratedRegex(@"\bCREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\b", RegexOptions.CultureInvariant)]
    private static partial Regex TriggerPattern();

    [GeneratedRegex(@"%ROWTYPE", RegexOptions.CultureInvariant)]
    private static partial Regex RowTypePattern();

    [GeneratedRegex(@"\bCONNECT\s+BY\b", RegexOptions.CultureInvariant)]
    private static partial Regex ConnectByPattern();

    [GeneratedRegex(@"\bFROM\s+DUAL\b", RegexOptions.CultureInvariant)]
    private static partial Regex DualPattern();

    [GeneratedRegex(@"\bROWNUM\b", RegexOptions.CultureInvariant)]
    private static partial Regex RowNumPattern();

    [GeneratedRegex(@"\bSTANDARD_HASH\s*\(", RegexOptions.CultureInvariant)]
    private static partial Regex StandardHashPattern();

    [GeneratedRegex(@"\s+", RegexOptions.CultureInvariant)]
    private static partial Regex Whitespace();
}
