// Copyright (c) Microsoft. All rights reserved.

namespace OracleFormsMigrationFleet.Fleet;

/// <summary>What actually carries out a phase, so the console can stop implying every phase is agentic.</summary>
public enum PhaseEngine
{
    /// <summary>No adapter is registered. The phase appears in the plan and nothing performs it.</summary>
    NotImplemented,

    /// <summary>Parsing and emitting only. No model is consulted and the output is reproducible.</summary>
    Deterministic,

    /// <summary>Deterministic work, then a model reads the result and adds advisory findings.</summary>
    DeterministicWithModelReview,

    /// <summary>Deterministic database work; a model may propose bounded routine-body repairs that the compiler accepts or rejects.</summary>
    DeterministicWithBoundedModelRepair,
}

/// <summary>
/// Who owns a phase, what performs it, and on which model deployment if any.
///
/// <see cref="Role"/> is a label on the plan, not a dispatch target: no code selects behaviour from it.
/// Saying so here is the point, because a list of specialist role names invites the opposite assumption.
/// </summary>
public sealed record PhaseAttribution(
    MigrationPhase Phase,
    FleetRole Role,
    PhaseEngine Engine,
    string? ModelDeployment,
    string Summary);

/// <summary>Which model backs a named capability, for display next to the work it performs.</summary>
public sealed record ModelAttribution(string Capability, string? Deployment, string Summary);

public sealed record FleetAttribution(
    IReadOnlyList<PhaseAttribution> Phases,
    IReadOnlyList<ModelAttribution> Models,
    IReadOnlyList<string> Disclaimers);

/// <summary>
/// Describes, without contacting anything, which part of the system performs each phase. Pure by design:
/// the answer must not depend on whether a model happens to be reachable.
/// </summary>
public static class FleetAttributionMap
{
    public static FleetAttribution Describe(
        IReadOnlyCollection<MigrationPhase> registeredAdapters,
        string? conversationDeployment,
        string? reviewDeployment)
    {
        ArgumentNullException.ThrowIfNull(registeredAdapters);

        List<PhaseAttribution> phases = [];
        foreach (PhaseOwnership ownership in MigrationRunPlanner.Lifecycle)
        {
            bool implemented = registeredAdapters.Contains(ownership.Phase);
            bool modelConfigured = !string.IsNullOrWhiteSpace(reviewDeployment);
            bool reviewed = implemented
                && modelConfigured
                && ownership.Phase is MigrationPhase.ApplicationCodeConversion or MigrationPhase.DatabaseConversion;
            bool repaired = implemented
                && modelConfigured
                && ownership.Phase == MigrationPhase.SandboxDataMigration;

            PhaseEngine engine = (implemented, reviewed, repaired) switch
            {
                (false, _, _) => PhaseEngine.NotImplemented,
                (true, true, _) => PhaseEngine.DeterministicWithModelReview,
                (true, _, true) => PhaseEngine.DeterministicWithBoundedModelRepair,
                _ => PhaseEngine.Deterministic,
            };

            phases.Add(new PhaseAttribution(
                ownership.Phase,
                ownership.Owner,
                engine,
                reviewed || repaired ? reviewDeployment : null,
                engine switch
                {
                    PhaseEngine.NotImplemented =>
                        "No adapter is registered. The plan covers this phase in writing; nothing performs it.",
                    PhaseEngine.DeterministicWithModelReview =>
                        $"Generated by deterministic code, then read by {reviewDeployment} for advisory findings that authorize nothing.",
                    PhaseEngine.DeterministicWithBoundedModelRepair =>
                        $"Database work is deterministic. For compiler-rejected routines only, {reviewDeployment} may propose body-only repairs; PostgreSQL accepts or rejects them.",
                    _ => "Performed by deterministic code. No model is consulted and the output is reproducible.",
                }));
        }

        List<ModelAttribution> models =
        [
            new("Conversation and tool calling",
                conversationDeployment,
                "Answers questions about a plan and calls the deterministic fleet as tools. It cannot change a plan, a gate, or an attestation."),
            new("Artifact review",
                reviewDeployment,
                "Reads generated database and application artifacts and reports suspected defects. Findings are written separately and authorize nothing."),
            new("Bounded routine repair",
                reviewDeployment,
                "May propose body-only repairs for routines PostgreSQL rejected. The compiler, not the model, accepts a revision."),
        ];

        return new FleetAttribution(
            phases,
            models,
            [
                "Specialist role names label ownership in the plan. No code selects behaviour from a role, so the roles are not independent agents.",
                "Every gate, approval, attestation, and the target platform recommendation is decided by deterministic code. No model output reaches any of them.",
                "When configured, the review model may read generated application or database artifacts and may propose bounded repairs only for compiler-rejected routine bodies. It is not called for every phase or every run.",
            ]);
    }
}
