namespace OracleFormsMigrationFleet.Fleet;

/// <summary>Deterministic treatment of Oracle Forms concerns that schema conversion tools do not resolve.</summary>
public static class LegacyModernizationCatalog
{
    public static IReadOnlyDictionary<WorkloadSignal, LegacyRiskDefinition> Risks { get; } =
        new Dictionary<WorkloadSignal, LegacyRiskDefinition>
        {
            [WorkloadSignal.ClientSidePlSql] = Risk(Severity.High, "Client-side PL/SQL requires allocation",
                "Separate Forms client logic from database-resident PL/SQL before conversion; SSMA assesses database objects, not Forms runtime logic.",
                "CT-CLIENT-PLSQL", "Allocate client-side PL/SQL to the new application tier or an explicitly reviewed database service.",
                EvidenceKind.FormsModuleSource, EvidenceKind.FormsXmlExport),
            [WorkloadSignal.FormsTriggerNavigationLogic] = Risk(Severity.High, "Forms interaction semantics require redesign",
                "Trigger order, item/block validation, navigation, and commit behavior must be reconstructed as explicit application workflows.",
                "CT-FORMS-SEMANTICS", "Model and regression-test Forms trigger, navigation, validation, and transaction semantics in the replacement UI.",
                EvidenceKind.FormsModuleSource, EvidenceKind.FormsXmlExport, EvidenceKind.BusinessProcessCatalog),
            [WorkloadSignal.MultiRecordBlocks] = Risk(Severity.High, "Multi-record blocks need a scalable editing model",
                "A one-to-one browser rendering of large multi-record blocks can lose keyboard efficiency and create unacceptable data-loading and rendering costs.",
                "CT-EDITABLE-GRIDS", "Prototype editable grids with keyboard workflows, batch save semantics, virtualization or server-side paging, validation, and representative-volume performance tests.",
                EvidenceKind.FormsModuleSource, EvidenceKind.FormsXmlExport, EvidenceKind.BusinessProcessCatalog, EvidenceKind.WorkloadProfile, EvidenceKind.TestBaseline),
            [WorkloadSignal.EnterQueryMode] = Risk(Severity.High, "ENTER-QUERY behavior requires explicit replacement",
                "Forms query-by-example is a modal, keyboard-driven workflow that generic search pages do not preserve automatically.",
                "CT-QUERY-BEHAVIOR", "Define a filter-row or search-panel replacement and prove that representative ENTER-QUERY criteria, operators, keyboard flows, and result semantics remain available.",
                EvidenceKind.FormsModuleSource, EvidenceKind.FormsXmlExport, EvidenceKind.BusinessProcessCatalog, EvidenceKind.TestBaseline),
            [WorkloadSignal.PostQueryLogic] = Risk(Severity.High, "POST-QUERY logic must be allocated deliberately",
                "POST-QUERY triggers can derive display values or apply business behavior after fetch; dropping or blindly moving them can change results and create per-row performance problems.",
                "CT-POST-QUERY", "Classify POST-QUERY logic as presentation, service, or data logic; replace row-by-row enrichment with tested set-based or service behavior where appropriate.",
                EvidenceKind.FormsModuleSource, EvidenceKind.FormsXmlExport, EvidenceKind.PlSqlProgramUnit, EvidenceKind.BusinessProcessCatalog, EvidenceKind.TestBaseline),
            [WorkloadSignal.SharedPllOrObjectLibraries] = Risk(Severity.High, "Shared Forms libraries create hidden coupling",
                "PLL and OLB dependencies must be expanded transitively; module-only inventories undercount shared behavior.",
                "CT-SHARED-LIBRARIES", "Build the transitive PLL/OLB dependency graph and assign each shared capability to a replacement service or component.",
                EvidenceKind.SharedLibrarySource, EvidenceKind.ObjectLibrarySource),
            [WorkloadSignal.JavaBeansOrPjc] = Risk(Severity.High, "Java client extensions require replacement",
                "Java Beans and Pluggable Java Components run in the Forms client model and do not transfer to a browser application.",
                "CT-JAVA-EXTENSIONS", "Inventory Java Beans and PJCs, then replace each with a supported browser, service, or device-integration pattern.",
                EvidenceKind.FormsModuleSource, EvidenceKind.IntegrationInventory),
            [WorkloadSignal.WebUtilOleOrJacob] = Risk(Severity.Critical, "Desktop automation blocks browser parity",
                "WebUtil, OLE, and Jacob integrations depend on client-machine capabilities that require security-reviewed redesign.",
                "CT-DESKTOP-INTEGRATION", "Replace WebUtil/OLE/Jacob behavior with controlled upload, download, printing, or device services and obtain security approval.",
                EvidenceKind.FormsModuleSource, EvidenceKind.IntegrationInventory),
            [WorkloadSignal.HostCommandUsage] = Risk(Severity.Critical, "Host command execution must be removed",
                "HOST and operating-system command execution cannot be carried into a managed browser or database tier.",
                "CT-HOST-COMMANDS", "Eliminate HOST calls or move required operations to an authenticated, allow-listed service with auditable execution.",
                EvidenceKind.FormsModuleSource, EvidenceKind.IntegrationInventory),
            [WorkloadSignal.OracleReportsIntegration] = Risk(Severity.High, "Oracle Reports is a separate migration workstream",
                "Forms-to-Reports calls, parameters, output formats, printers, and schedules are not covered by Forms UI or SSMA database conversion.",
                "CT-REPORTS", "Inventory Oracle Reports entry points, parameters, destinations, schedules, and regulatory output fidelity; select a replacement reporting platform.",
                EvidenceKind.OracleReportsInventory, EvidenceKind.BusinessProcessCatalog),
            [WorkloadSignal.DynamicSql] = Risk(Severity.High, "Dynamic SQL limits automated conversion",
                "Runtime-constructed SQL needs observed statement samples and manual semantic review beyond static source conversion.",
                "CT-DYNAMIC-SQL", "Capture representative dynamic SQL, parameterization, plans, and error paths before manual conversion and performance testing.",
                EvidenceKind.PlSqlProgramUnit, EvidenceKind.WorkloadProfile),
            [WorkloadSignal.OracleAdvancedQueuing] = Risk(Severity.High, "Oracle AQ requires an integration redesign",
                "Oracle Advanced Queuing semantics do not map directly to Azure SQL queues and require a messaging architecture decision.",
                "CT-AQ", "Map AQ producers, consumers, ordering, retries, payloads, and transactions to a reviewed Azure messaging pattern.",
                EvidenceKind.DatabaseSchemaExport, EvidenceKind.IntegrationInventory),
            [WorkloadSignal.VpdOrRowLevelSecurity] = Risk(Severity.Critical, "Oracle VPD policy parity is mandatory",
                "Row-level access policy behavior must be re-specified and security-tested; mechanical schema conversion is insufficient.",
                "CT-VPD", "Translate VPD/application-context policies into an approved authorization and row-level-security design with negative tests.",
                EvidenceKind.DatabaseSchemaExport, EvidenceKind.AuthenticationTopology, EvidenceKind.ComplianceConstraint),
            [WorkloadSignal.NlsSemanticDependency] = Risk(Severity.High, "NLS-dependent behavior can change results",
                "Implicit date, number, collation, time-zone, and character conversions can differ between Oracle and Azure SQL.",
                "CT-NLS", "Make NLS-dependent conversions explicit and test locale, collation, Unicode, time-zone, date, and numeric edge cases.",
                EvidenceKind.PlSqlProgramUnit, EvidenceKind.DataProfile),
            [WorkloadSignal.EmptyStringNullDependency] = Risk(Severity.High, "Oracle empty-string NULL semantics differ",
                "Oracle treats zero-length character strings as NULL while SQL Server distinguishes them.",
                "CT-NULL-SEMANTICS", "Identify empty-string assumptions in constraints, predicates, PL/SQL, APIs, and UI validation; define and test target behavior.",
                EvidenceKind.PlSqlProgramUnit, EvidenceKind.DataProfile, EvidenceKind.FormsModuleSource),
            [WorkloadSignal.PessimisticLocking] = Risk(Severity.High, "Forms locking and commit behavior needs concurrency tests",
                "Long-lived Forms sessions and record locking do not map safely to stateless web request lifetimes without redesign.",
                "CT-CONCURRENCY", "Define optimistic or bounded transaction behavior and test lost updates, deadlocks, retries, and multi-user workflows.",
                EvidenceKind.FormsModuleSource, EvidenceKind.WorkloadProfile, EvidenceKind.BusinessProcessCatalog),
            [WorkloadSignal.LegacyAuthentication] = Risk(Severity.High, "Legacy authentication requires identity redesign",
                "Database credentials, Forms authentication, and legacy SSO cannot be assumed to map to Microsoft Entra ID.",
                "CT-IDENTITY", "Inventory users, roles, impersonation, database accounts, SSO, service identities, and segregation-of-duties requirements.",
                EvidenceKind.AuthenticationTopology, EvidenceKind.ComplianceConstraint),
            [WorkloadSignal.InaccessibleSource] = Risk(Severity.Critical, "Authoritative source is inaccessible",
                "Binary modules, missing libraries, or an unavailable build environment prevent reliable static analysis and conversion planning.",
                "CT-SOURCE-RECOVERY", "Recover authoritative FMB/MMB/PLL/OLB/RDF sources and establish a reproducible export/build process before committing to conversion.",
                EvidenceKind.FormsModuleSource, EvidenceKind.SharedLibrarySource, EvidenceKind.OracleReportsInventory),
            [WorkloadSignal.MissingRegressionBaseline] = Risk(Severity.High, "No behavioral test oracle exists",
                "Without representative workflows and expected results, generated or rewritten code cannot demonstrate functional parity.",
                "CT-CHARACTERIZATION", "Capture critical user journeys, data fixtures, outputs, timings, and failure paths as characterization tests before replacement.",
                EvidenceKind.TestBaseline, EvidenceKind.BusinessProcessCatalog),
            [WorkloadSignal.OnlineCutoverRequired] = Risk(Severity.High, "Low-downtime data movement needs separate tooling",
                "Oracle-to-Azure SQL DMS-backed movement is an offline preview path; continuous synchronization requires a validated replication product and reconciliation plan.",
                "CT-ONLINE-CUTOVER", "Select and prove a supported CDC/replication path, reconciliation controls, cutover freeze, fallback, and data-loss objective.",
                EvidenceKind.CutoverAndRollbackPlan, EvidenceKind.DataProfile, EvidenceKind.WorkloadProfile),
            [WorkloadSignal.CoexistenceRequired] = Risk(Severity.High, "Coexistence creates dual-system consistency risk",
                "Incremental replacement requires explicit ownership of data and business operations while Oracle and the replacement run together.",
                "CT-COEXISTENCE", "Define bounded contexts, system-of-record ownership, synchronization, compatibility APIs, reconciliation, and rollback for each migration wave.",
                EvidenceKind.BusinessProcessCatalog, EvidenceKind.IntegrationInventory, EvidenceKind.CutoverAndRollbackPlan),
            [WorkloadSignal.LowOrNoBusinessUsage] = Risk(Severity.Medium, "Retirement may be safer than conversion",
                "Low usage should trigger business-owner confirmation and retention analysis before funding a rewrite.",
                "CT-RETIRE", "Validate usage and ownership, export required records, provide compliant read-only access, and decommission the application and licenses.",
                EvidenceKind.UsageAndBusinessValue, EvidenceKind.ComplianceConstraint),
            [WorkloadSignal.PackageReplacementAvailable] = Risk(Severity.Medium, "Package replacement may avoid custom redevelopment",
                "A product-fit option must be compared on process fit, integration, data portability, customization, lock-in, and total cost rather than feature checklists alone.",
                "CT-PACKAGE-FIT", "Run a fit-to-standard assessment and proof of critical workflows before selecting custom redevelopment.",
                EvidenceKind.ReplacementProductFit, EvidenceKind.BusinessProcessCatalog, EvidenceKind.IntegrationInventory),
            [WorkloadSignal.RegulatoryRetentionOnly] = Risk(Severity.High, "Records require preservation, not an active Forms runtime",
                "Retention obligations may be met by immutable archival, search, legal hold, and controlled read-only access instead of migrating transactional behavior.",
                "CT-ARCHIVE", "Define retention, legal hold, evidentiary integrity, search, access, deletion, and audit controls for a read-only archive.",
                EvidenceKind.ComplianceConstraint, EvidenceKind.UsageAndBusinessValue, EvidenceKind.DataProfile),
        };

    private static LegacyRiskDefinition Risk(
        Severity severity,
        string title,
        string detail,
        string taskId,
        string taskDescription,
        params EvidenceKind[] preferredEvidence) =>
        new(severity, title, detail, taskId, taskDescription, preferredEvidence);
}

public sealed record LegacyRiskDefinition(
    Severity Severity,
    string Title,
    string Detail,
    string TaskId,
    string TaskDescription,
    IReadOnlyList<EvidenceKind> PreferredEvidence);